name: 'TypoScan'
description: 'Scan repository for typos'
inputs:
  repository:
    description: 'Repository owner/name string'
    required: true
    default: ''
  scan-exclude-match:
    description: 'Array on file paths to avoid typo scan'
    required: true
    default: '[''typos/**'', ''public/**'']'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Validate input repository exists 
      run: |
        if curl --head --silent --fail https://github.com/${{ inputs.repository }} 2> /dev/null;
        then
          echo "This page exists."
        else
          echo "This page does not exist."
          exit 1;
        fi
      shell: bash
    
    - name: Checkout repository TO SCAN
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        path: repoToScan

    - name: Checkout repository with typo binary
      uses: actions/checkout@v3
      with:
        repository: open-source-crawler-test/typo-scan-test
        path: typoBinary
  
    - name: 🛠️ Set up typos binary and toml config file
      run: |
        mv ./typoBinary/bin/typos repoToScan
        cd repoToScan
        touch _typos.toml
        echo "[files]" >> _typos.toml
        echo "extend-exclude = ${{ inputs.scan-exclude-match }}" >> _typos.toml
        # echo "extend-exclude = ['typos/**', 'public/**']" >> _typos.toml
        cat _typos.toml
        mkdir typos-report
        cd typos-report
        touch typos.txt
        touch typos.diff
        cd ..
        cd ..
      shell: bash

    - name: 🚫 Preform typo scan
      run: |
        cd repoToScan
        chmod +x typos
        ./typos >> typos-report/typos.txt || true
        ./typos >> typos-report/typos.diff --diff || true
        cd ..
      shell: bash

    - name: Generate report metadata
      run: |
        cd repoToScan/typos-report
        touch README.md
        echo "# Typo Report Metadata" >> README.md
        echo "" >> README.md
        echo "Repository:" >> README.md
        echo '[${{ env.REPO_URL }}](https://github.com/${{ env.REPO_URL }})' >> README.md
        echo "" >> README.md
        echo "Analysis Date:" >> README.md
        echo "" >> README.md
        date >> README.md
        echo "" >> README.md
        echo "Size: $(ls -alh typos-report/)" >> README.md
        echo "" >> README.md
        cat README.md >> $GITHUB_JOB_SUMMARY
        cd ../..
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: typos-report
        path: repoToScan/typos-report