name: 'TypoScan'
description: 'Scan repository for typos'
inputs:
  repository:
    description: 'Repository owner/name string'
    required: true
    default: ''
  scan-exclude-match:
    description: 'Array on file paths to avoid typo scan'
    required: true
    default: '[''typos/**'', ''public/**'']'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Validate input repository exists 
      run: |
        if curl --head --silent --fail https://github.com/${{ inputs.repository }} 2> /dev/null;
        then
          echo "This page exists."
        else
          echo "This page does not exist."
          exit 1;
        fi
      shell: bash
    
    - name: Checkout repository with typo binary
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }})
        path: repoToScan

    - name: Checkout repository with typo binary
      uses: actions/checkout@v3
      with:
        repository: open-source-crawler-test/typo-scan-test
        path: typoBinary

    - name: 🛠️ Create spell checker config file
      run: |
        mv typoBinary/bin/typo && repoToScan
        cd repoToScan
        touch _typos.toml
        echo "[files]" >> _typos.toml
        echo "extend-exclude = ${{ inputs.scan-exclude-match }}" >> _typos.toml
        # echo "extend-exclude = ['typos/**', 'public/**']" >> _typos.toml
        cat _typos.toml
        mkdir typos-report
        cd typos-report
        touch typos.txt
        touch typos.diff
        cd ..
        cd ..
      shell: bash

    - name: 🚫 Preform typo scan
      run: |
        cd repoToScan
        ${{ github.workspace }}/typos >> typos-report/typos.txt || true
        ${{ github.workspace }}/typos >> typos-report/typos.diff --diff || true
        cd ..
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: typos-report
        path: repoToScan/typos-report