name: Test Action
on: 
 push:
 workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run this action to test it
        uses: ./
        with:
          repository: npm/registry
          scan-exclude-match: '[''typos/**'', ''public/**'']'